- name: Check if Homebrew is already installed
  stat:
    path: /usr/local/bin/brew
  register: b
  tags:
    - brew
    - core
    - install

- name: Install Homebrew
  script: install-homebrew.sh
  when: not b.stat.exists
  tags:
    - brew
    - install
    - core

- name: Check for Brewfile.
  stat:
    path: "$HOME/.dotfiles/Brewfile"
  register: homebrew_brewfile
  check_mode: false
  tags:
    - brew
    - install
    - core

- name: Install from Brewfile.
  command: "brew bundle chdir=$HOME/.dotfiles"
  when: homebrew_brewfile.stat.exists
  tags:
    - brew
    - install
    - core
